### ISSUE TITLE
Package Gaia

### ISSUE THREAD

**Issue by JonathanLorimer** [informalsystems/cosmos.nix#13]

**Comment by soareschen** [comment]
We might need to need this in few months for end-to-end testing. One thing to keep in mind is that we will have to build different major versions of Gaia for testing, for example v4.2 and v5.0. So it would be good to make the Nix module modular such that the user can instantiate Gaia with different versions of source code.

**Comment by JonathanLorimer** [comment]
That's a good point. That should be fairly straightforward, we can specify a different input per version, and set the rev of the input to the tag of that major version release. I am thinking `3.0.1`, `4.2.1`, and `5.0.5` would be a reasonable place to start?

**Comment by soareschen** [comment]
Sounds good. Just 4.2.1 and 5.0.5 should be fine. I think the ecosystem has mostly moved to v4 now, and are beginning to move to v5.

**Comment by JonathanLorimer** [comment]
despite https://github.com/informalsystems/cosmos.nix/pull/8 I am leaving this open until I add support for v5 and v4
