### ISSUE TITLE
Publish cosmos.nix to FlakeHub

### ISSUE THREAD

**Issue by romac** [informalsystems/cosmos.nix#152]
See the blog post for more info: https://determinate.systems/posts/introducing-flakehub

**Comment by romac** [comment]
What do you think @JonathanLorimer?

**Comment by JonathanLorimer** [comment]
I'm good friends with determinate systems, and I love everything they do. I'll get this published today! Thanks for making the issue @romac

**Comment by romac** [comment]
If I understand correctly, we need to start versioning the repo with tags in order to publish it, right?

If so, maybe we should use the occasion to start maintaining a proper changelog as well?

**Comment by romac** [comment]
For some other projects at Informal, we use [`unclog`](https://github.com/informalsystems/unclog) but that might be a bit overkill here. I am fine generating it from Git commits :)

**Comment by romac** [comment]
I think that's perfectly fine for this project. Unclog brings quite a bit of overhead that I think only makes sense for larger projects with many sub-components and many concurrent PRs. Let's go with the GitHub action then!

**Comment by JonathanLorimer** [comment]
Sounds, good. I will add the changelog to CI, and cut an initial release tonight!

**Comment by JonathanLorimer** [comment]
@romac https://flakehub.com/flake/informalsystems/cosmos.nix looks pretty good!

**Comment by romac** [comment]
Now live :) https://flakehub.com/flake/informalsystems/cosmos.nix
