### ISSUE TITLE
with nix on ci and devshell not need for precommit hooks

### ISSUE THREAD

**Issue by dzmitry-lahoda** [informalsystems/cosmos.nix#156]
```
    # Has to follow flake-utils in order to get aarch64-darwin
    # can revert after https://github.com/cachix/pre-commit-hooks.nix/pull/142
    pre-commit-hooks.inputs.flake-utils.follows = "flake-utils";
    pre-commit-hooks.inputs.nixpkgs.follows = "nixpkgs";
``` 

just remove and do ci checks via nix commands

https://www.youtube.com/watch?v=RAelLqnnOp0

**Comment by dzmitry-lahoda** [comment]
hooks are needed for LFS resolution and other like that itegration, not for CI checks.

**Comment by JonathanLorimer** [comment]
I don't necessarily agree that pre-commit-hooks are not appropriate here, but I have been a bit torn on them recently. I have removed them in https://github.com/informalsystems/cosmos.nix/pull/178 so closing this for now.

**Comment by dzmitry-lahoda** [comment]
yeah, i know one use full case to use hooks - to avoid publush private keys to git :) which is not the case here. 

also some nix shell wrappers allow optin to hooks when one shells into. so it is flexible.
