### ISSUE TITLE
feat: add solidity IBC builds

### ISSUE THREAD

**Issue by dzmitry-lahoda** [informalsystems/cosmos.nix#162]
here is PR for shells https://github.com/hyperledger-labs/yui-ibc-solidity/pull/214

afaik people run ETH Cosmos IBC via TEE light clients proxies there. also they do IBC to some corporate networks. and some mock clients

**Comment by dzmitry-lahoda** [comment]
should these go here? i guess yes. similar how ethereum.nix aggegates forge nix. so this repo aggregates ibc (because some repo should be bigger than cosmos, include ibc and cosmwasm on other vms/chains, this fits well imho)

**Comment by JonathanLorimer** [comment]
It would be cool to support a default cosmos-sdk development shell. Is that what you are proposing here?

**Comment by dzmitry-lahoda** [comment]
I am asking here if IBC for EVM in Solidity builds should go to cosmos.nix repo?
