### ISSUE TITLE
feat: add cosmos to nix registry and/or flakehub

### ISSUE THREAD

**Issue by dzmitry-lahoda** [informalsystems/cosmos.nix#173]
https://github.com/NixOS/flake-registry

so can `nix run cosmso#whatever`

**Comment by dzmitry-lahoda** [comment]
and/or here publish to https://flakehub.com/

**Comment by JonathanLorimer** [comment]
I believe we are already published on flake hub https://flakehub.com/flake/informalsystems/cosmos.nix

**Comment by JonathanLorimer** [comment]
I believe we are already published on flake hub https://flakehub.com/flake/informalsystems/cosmos.nix 

Closing for now. Feel free to re-open if there is something more to be done.
