### ISSUE TITLE
chore: consider using microvm.nix instead of builtin qemu directly

### ISSUE THREAD

**Issue by dzmitry-lahoda** [informalsystems/cosmos.nix#186]
seems is is bullish

https://www.youtube.com/watch?v=iGteDsnlCoY

https://github.com/astro/microvm.nix/tree/89bb7a5230a4820736a43e058c8d2a2c560d672b

peek you vmm depending on use case,

both test and prod oriented

many stars (754 for nix project is huge)

**Comment by JonathanLorimer** [comment]
YES! I have been looking at this repo for a while, but hadn't found a use case. This is a good one!

**Comment by dzmitry-lahoda** [comment]
qemu tests worked, so i guess microvm will run serveral times faster and more debuggable by mere mortals.

so think first need to abstract chain into modules https://github.com/informalsystems/cosmos.nix/issues/187 .

so that whatever runner module (qemu/microvm/containers) can reuse module.

but for now will close. can reopen if needed or create new task.
