### ISSUE TITLE
ci is down

### ISSUE THREAD

**Issue by dzmitry-lahoda** [informalsystems/cosmos.nix#226]
building '/nix/store/0ik1fl7brsa8frgkm3nrc9d2d556r7wq-beaker-0.1.8.drv'...
error (ignored): error: cannot unlink '/tmp/nix-build-hermes-v1.7.4.drv-0/source/target/x86_64-unknown-linux-gnu/release/deps': Directory not empty
error (ignored): error: cannot unlink '/tmp/nix-build-beaker-0.1.8.drv-0': Directory not empty
error: writing to file: No space left on device
Error: Process completed with exit code 1.

**Comment by dzmitry-lahoda** [comment]
i suggest to use github big instances with magic nix cache. seems most husstle free setup

**Comment by dzmitry-lahoda** [comment]
magix  nix cache with ubuntu m gh large instances work hasstle free for me.

**Comment by dzmitry-lahoda** [comment]
this setup also works well for half year https://github.com/ComposableFi/env/blob/main/ci.md

**Comment by JonathanLorimer** [comment]
I don't think magic cache is necessary, given we have a cache (although there are definitely a lot of improvements I could do to our existing cache)

We could definitely use beefier CI machines, at some point I may have to set up self hosted runners on AWS (that's where I have the cache hosted right now).

I don't know if Informal is open to paying for bigger GH hosted instances.

**Comment by JonathanLorimer** [comment]
I think there is probably some work we could do to optimize our CI workflows. Right now CI builds the whole world everytime (although the cache mitigates builds, it doesn't mitigate the space used since cached artifacts are downloaded). We could theoretically just check new derivations and changed derivations, but this is pretty complicated to facilitate I think.

**Comment by JonathanLorimer** [comment]
I''m not sure what you meant by Nix's cleanup options, I am not sure if we GC mid nix command. And our nix installer automatically sets `auto-optimise-store` https://github.com/DeterminateSystems/nix-installer-action?tab=readme-ov-file#installation-differences

**Comment by dzmitry-lahoda** [comment]
works well for a while
