### ISSUE TITLE
can't create #cosmos-shell with nix develop, image-centauri.json: unexpected end of file

### ISSUE THREAD

**Issue by zarkone** [informalsystems/cosmos.nix#236]
Hello! 

Getting a weird error when I'm trying to jump into cosmos-shell:

```
nix develop .#cosmos-shell
```
```
error: builder for '/nix/store/4j30jdpynq12vh1r2phpj2in9xgp55gn-nix-shell-env.drv' failed with exit code 2;
       last 1 log lines:
       > /nix/store/61alrkg9y9vyf0ij2kvqswp4dlws391p-image-centauri.json: line 56: syntax error: unexpected end of file
       For full logs, run 'nix-store -l /nix/store/4j30jdpynq12vh1r2phpj2in9xgp55gn-nix-shell-env.drv'.
```

which is weird because this `image-centauri.json` is a totally valid json, apart from, maybe, no newline at the end of file. 

Any ideas what could happen here? 

Thank you!

**Comment by dzmitry-lahoda** [comment]
hello. was you able  build image and run centairy directly?  

other note, may be disable images from shell for now?

as i recall i did tested image directly, so now not so sure.

**Comment by zarkone** [comment]
hello @dzmitry-lahoda ! thanks! My ultimate goal was to get into env with ignite-cil present. I realized that I can use `nix run` also for ignite, and it worked, however, I had problems with scaffolding right away because it creates a temp executable for swagger, which is dinamically linked. Not sure it is possible to address from the outside of ignite-cli. 

> other note, may be disable images from shell for now?

removing centauri from pkgs helps, in that case -- thanks! :+1: 

(going to close this one for now)
