### ISSUE TITLE
`gaiad` binary built from Nix do not contain version information

### ISSUE THREAD

**Issue by soareschen** [informalsystems/cosmos.nix#53]
The original `gaia` build script contains some magic in the [Makefile](https://github.com/cosmos/gaia/blob/v4.2.1/Makefile#L64-L69) that injects version info to the code before compilation.

Other than that, the information about build dependencies is retried using [`debug.ReadBuildInfo()`](https://github.com/cosmos/cosmos-sdk/blob/v0.44.3/version/version.go#L89-L90), which is apparently only [available only in binaries built with module support](https://pkg.go.dev/runtime/debug#ReadBuildInfo) and is missing in the Nix build.

Without these information, the GRPC query to the gaiad version info only return empty strings and empty arrays. This impacts the ability for clients such as Hermes to determine the version of the Gaia full node it is communicating to.

**Comment by JonathanLorimer** [comment]
Oh, interesting. I wonder if we can make `buildGoApplicatoin` leverage the makefile. If not we probably have to copy that behaviour, which isn't impossible with the metadata nix has lying around (both in the nix files and in the flake.lock)

**Comment by soareschen** [comment]
I think an alternative is that we could patch the source file to directly replace the empty string fields with the appropriate metadata. Although that would mean that we have to figure out the proper format of the data, and whether to automatically regenerate the patch files when there is a source update.

**Comment by JonathanLorimer** [comment]
hmmmmm, I am pretty sure `gomod2nix` only works on go modules. Maybe I am missing something here. Also, to clarify, does the Makefile inject infromation about the `cosmos-sdk` version or the `gaia` version? The ldflags seem to suggest cosmos-sdk. Do you have a link to where the values get injected in the gaia code? Patching the metadata in would actually be fairly trivial, although admittedly hacky.

**Comment by JonathanLorimer** [comment]
Okay, so it looks like `ldflags` is a pretty standard way to inject version information into go projects at build time. I just need to see if the nix tool that we use to generate go derivations supports it (I think it does). Hoping to have a solution up soon!

**Comment by JonathanLorimer** [comment]
Is there a reason the `VERSION` is calculated from the branch name and commit hash? It seems to me that the commit hash should be enough to uniquely identify the version. https://github.com/cosmos/gaia/blob/v4.2.1/Makefile#L6-L13

**Comment by JonathanLorimer** [comment]
@soareschen is this still an issue?

**Comment by JonathanLorimer** [comment]
@romac Can we confirm if this is still an issue or not?

**Comment by soareschen** [comment]
I think it has been fixed. Closing this.
