### ISSUE TITLE
Package Wasmd

### ISSUE THREAD

**Issue by soareschen** [informalsystems/cosmos.nix#75]
[Wasmd](https://github.com/CosmWasm/wasmd) is a Gaia fork with smart contract capability. Having this available on Cosmos.nix will make it easier for CosmWasm developers to develop and test smart contract using Cosmos.nix.

**Comment by JonathanLorimer** [comment]
Lucky for you, I just figured out how to package chains that depend on wasmd! Should be straight forward to package this!
