### ISSUE TITLE
Do we need to package Cosmos-SDK?

### ISSUE THREAD

**Issue by JonathanLorimer** [informalsystems/cosmos.nix#9]
Is there any executable software in the cosmos-sdk? My understanding is that it is intended to be a library used by blockchain developers. I think the [cosmovisor](https://github.com/cosmos/cosmos-sdk/tree/master/cosmovisor) is worth packaging, since it is its own executable, but other than that I can't find anything.

**Comment by JonathanLorimer** [comment]
@soareschen

**Comment by soareschen** [comment]
You are right that we probably don't need to package cosmos-sdk itself. Instead we can package gaia, which is essentially a lightweight wrapper around cosmos-sdk as an all-in-one executable.

**Comment by JonathanLorimer** [comment]
Cool, thanks for the response. I will package `cosmovisor` though, as that looks pretty useful!
